### ISSUE TITLE
Imposible to autorise after registration

### ISSUE THREAD

**Issue by nik9str** [nc-student-group/phone-company#103]
Registration on nik9str@gmail.com
Password: rootroot+
After changing password autorisation became possible
http://joxi.ru/J2bx3Y9i44babr

**Comment by serhiizem** [comment]
Possible duplicate of https://github.com/nc-student-group/phone-company/issues/107

**Comment by serhiizem** [comment]
Issue was not related to the code. Closed

**Comment by serhiizem** [comment]
Problem unsolved as it is related to ShaPasswordEncoder implementation. The only solution is not to include "+" in password.
